sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t docker-app -f Dockerfile-test .
script:
  - docker run -e CI=true docker-app npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-798521421267'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $user
  secret_access_key: $pwd